# Generated by Django 6.0.6 on 2026-06-29 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField()),
                ('startDate', models.DateTimeField()),
                ('monthlyPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField()),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.student')),
            ],
        ),
    ]
