# Generated by Django 6.0.6 on 2026-06-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='studentId',
            new_name='student',
        ),
    ]
